apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-httpgo.fullname" . }}
  labels:
    {{- include "k8s-httpgo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "k8s-httpgo.selectorLabels" . | nindent 4 }}
